int A = 6;
int B = 7;
int C = 10;
int D = 9;
int E = 8;
int F = 5;
int G = 4;
int green = 3;
int red = 11;

void setup() {
pinMode(A, OUTPUT);
pinMode(B, OUTPUT);
pinMode(C, OUTPUT);
pinMode(D, OUTPUT);
pinMode(E, OUTPUT);
pinMode(F, OUTPUT);
pinMode(G, OUTPUT);
pinMode(green, OUTPUT);
pinMode(red, OUTPUT);
}
void nine(){
  digitalWrite(A, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(E, LOW);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
}
void eight(){
  digitalWrite(A, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(E, HIGH);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
}
void seven(){
  digitalWrite(A, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, LOW);
  digitalWrite(E, LOW);
  digitalWrite(F, LOW);
  digitalWrite(G, LOW);
}
void six(){
  digitalWrite(A, HIGH);
  digitalWrite(B, LOW);
  digitalWrite(C, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(E, HIGH);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
}
void five(){
  digitalWrite(A, HIGH);
  digitalWrite(B, LOW);
  digitalWrite(C, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(E, LOW);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
}
void four(){
  digitalWrite(A, LOW);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, LOW);
  digitalWrite(E, LOW);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
}
void three(){
  digitalWrite(A, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(E, LOW);
  digitalWrite(F, LOW);
  digitalWrite(G, HIGH);
}
void two(){
  digitalWrite(A, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(C, LOW);
  digitalWrite(D, HIGH);
  digitalWrite(E, HIGH);
  digitalWrite(F, LOW);
  digitalWrite(G, HIGH);
}
void one(){
  digitalWrite(A, LOW);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, LOW);
  digitalWrite(E, LOW);
  digitalWrite(F, LOW);
  digitalWrite(G, LOW);
}
void zero(){
  digitalWrite(A, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(E, HIGH);
  digitalWrite(F, HIGH);
  digitalWrite(G, LOW);
}
void breaktime(){
  digitalWrite(green, LOW);
  digitalWrite(red, LOW);

  digitalWrite(A, LOW);
  digitalWrite(B, LOW);
  digitalWrite(C, LOW);
  digitalWrite(D, LOW);
  digitalWrite(E, LOW);
  digitalWrite(F, LOW);
  digitalWrite(G, LOW);
}



void loop() {
digitalWrite(green, HIGH);
nine();
delay(1000);
eight();
delay(1000);
seven();
delay(1000);
six();
delay(1000);
five();
delay(1000);
four();
delay(1000);
three();
delay(140);
digitalWrite(green, HIGH);
delay(140);
digitalWrite(green, LOW);
delay(140);
digitalWrite(green, HIGH);
delay(140);
digitalWrite(green, LOW);
delay(140);
digitalWrite(green, HIGH);
delay(140);
digitalWrite(green, LOW);
delay(140);
digitalWrite(green, HIGH);
delay(140);
two();
digitalWrite(green, LOW);
delay(90);
digitalWrite(green, HIGH);
delay(90);
digitalWrite(green, LOW);
delay(90);
digitalWrite(green, HIGH);
delay(90);
digitalWrite(green, LOW);
delay(90);
digitalWrite(green, HIGH);
delay(90);
digitalWrite(green, LOW);
delay(90);
digitalWrite(green, HIGH);
delay(90);
digitalWrite(green, LOW);
delay(90);
digitalWrite(green, HIGH);
delay(90);
digitalWrite(green, LOW);
delay(90);
digitalWrite(green, HIGH);
delay(90);
one();
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
zero();
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
delay(55);
digitalWrite(green, HIGH);
delay(55);
digitalWrite(green, LOW);
breaktime();
delay(500);
digitalWrite(red, HIGH);
nine();
delay(1000);
eight();
delay(1000);
seven();
delay(1000);
six();
delay(1000);
five();
delay(1000);
four();
delay(1000);
three();
digitalWrite(red, LOW);
delay(140);
digitalWrite(red, HIGH);
delay(140);
digitalWrite(red, LOW);
delay(140);
digitalWrite(red, HIGH);
delay(140);
digitalWrite(red, LOW);
delay(140);
digitalWrite(red, HIGH);
delay(140);
digitalWrite(red, LOW);
delay(140);
digitalWrite(red, HIGH);
delay(140);
digitalWrite(red, LOW);
delay(140);
digitalWrite(red, HIGH);
delay(140);
two();
digitalWrite(red, LOW);
delay(90);
digitalWrite(red, HIGH);
delay(90);
digitalWrite(red, LOW);
delay(90);
digitalWrite(red, HIGH);
delay(90);
digitalWrite(red, LOW);
delay(90);
digitalWrite(red, HIGH);
delay(90);
digitalWrite(red, LOW);
delay(90);
digitalWrite(red, HIGH);
delay(90);
digitalWrite(red, LOW);
delay(90);
digitalWrite(red, HIGH);
delay(90);
digitalWrite(red, LOW);
delay(90);
digitalWrite(red, HIGH);
delay(90);
one();
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
zero();
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
delay(55);
digitalWrite(red, HIGH);
delay(55);
digitalWrite(red, LOW);
breaktime();
delay(500);
}
